/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.turtlekit2.warbot.controller;

import java.awt.Color;

/**
 * Classe permettant d'afficher le panneau de controle qui permettra
 * de gerer l'affichage sur le terrain tout au long du match.
 * Elle permettra en autre de:
 * <ul>
 * 	<li>faire apparaitre les cercles de percepts.<li>
 * 	<li>faire apparaitre les diverses informations concernant l'agent.</li>
 * 	<li>faire apparaitre l'agent.</li>
 * 	<li>faire apparaitre dans la console les messages echanges.</li>
 * 	<li>faire apparaitre dans la console les percepts observes par l'agent.</li>
 * </ul>
 * 
 * @author Bonnotte Jessy, Burc Pierre, Duplouy Olivier, Polizzi Mathieu
 *
 */
@SuppressWarnings("serial")
public class PanelControl extends javax.swing.JFrame {
    
    private static boolean							_MESSAGE_VIEWER = false;
    private static boolean							_PERCEPT_VIEWER = false;
    private static boolean							_INFO_VIEWER = false;
    private static boolean							_INFO_LOG_VIEWER = false;
    private static boolean							_AGENT_VIEWER = true;

    private static String							_victory = "";

    /**
     * Creates new form PanelControl
     */
    public PanelControl(String team1, String team2) {
        initComponents();
        setAlwaysOnTop(true);
        
        setLocationRelativeTo(null); 

        t1.setText(team1);
        t2.setText(team2);
    }
    
    @Override
    public void setVisible(boolean t){
    	super.setVisible(t);
    	init();
    }
    
    private void init(){
    	if(_PERCEPT_VIEWER){
        	perceptIndicator.setBackground(Color.GREEN);
        }else{
        	perceptIndicator.setBackground(Color.RED);
        }

        if(_INFO_VIEWER){
        	infoIndicator.setBackground(Color.GREEN);
        }else{
        	infoIndicator.setBackground(Color.RED);
        }

        if(_MESSAGE_VIEWER){
        	messageIndicator.setBackground(Color.GREEN);
        }else{
        	messageIndicator.setBackground(Color.RED);
        }

        if(_AGENT_VIEWER){
        	agentIndicator.setBackground(Color.GREEN);
        }else{
        	agentIndicator.setBackground(Color.RED);
        }

        if(_INFO_LOG_VIEWER){
        	infoLogIndicator.setBackground(Color.GREEN);
        }else{
        	infoLogIndicator.setBackground(Color.RED);
        }
    }
    
    public static boolean isMessageViewerChecked(){
    	return _MESSAGE_VIEWER;
    }
    
    public static boolean isPerceptViewerChecked(){
    	return _PERCEPT_VIEWER;
    }
    
    public static boolean isInfoViewerChecked(){
    	return _INFO_VIEWER;
    }
    
    public static boolean isInfoLogViewerChecked(){
    	return _INFO_LOG_VIEWER;
    }
    
    public static boolean isAgentViewerChecked(){
    	return _AGENT_VIEWER;
    }
    
    public static String getVictoriousTeam(){
    	return _victory;
    }
    
    public static void InitTeam(){
    	_victory = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        t1Win = new javax.swing.JButton();
        t2 = new javax.swing.JLabel();
        t2Win = new javax.swing.JButton();
        draw = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        messageSwitch = new javax.swing.JButton();
        messageIndicator = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        infoLogSwitch = new javax.swing.JButton();
        infoLogIndicator = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        perceptSwitch = new javax.swing.JButton();
        infoIndicator = new javax.swing.JPanel();
        perceptIndicator = new javax.swing.JPanel();
        infoSwitch = new javax.swing.JButton();
        agentSwitch = new javax.swing.JButton();
        agentIndicator = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/turtlekit2/warbot/controller/logo.jpg"))); // NOI18N

        t1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        t1.setText("team1");

        t1Win.setText("Victoire");
        t1Win.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1WinActionPerformed(evt);
            }
        });

        t2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        t2.setText("team2");

        t2Win.setText("Victoire");
        t2Win.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2WinActionPerformed(evt);
            }
        });

        draw.setText("EX AEQUO");
        draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        messageSwitch.setText("Messages");
        messageSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageSwitchActionPerformed(evt);
            }
        });

        messageIndicator.setBackground(new java.awt.Color(255, 0, 0));
        messageIndicator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        messageIndicator.setPreferredSize(new java.awt.Dimension(23, 23));

        javax.swing.GroupLayout messageIndicatorLayout = new javax.swing.GroupLayout(messageIndicator);
        messageIndicator.setLayout(messageIndicatorLayout);
        messageIndicatorLayout.setHorizontalGroup(
            messageIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        messageIndicatorLayout.setVerticalGroup(
            messageIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jLabel3.setText("Log");

        infoLogSwitch.setText("Informations");
        infoLogSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoLogSwitchActionPerformed(evt);
            }
        });

        infoLogIndicator.setBackground(new java.awt.Color(255, 0, 0));
        infoLogIndicator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        infoLogIndicator.setPreferredSize(new java.awt.Dimension(23, 23));

        javax.swing.GroupLayout infoLogIndicatorLayout = new javax.swing.GroupLayout(infoLogIndicator);
        infoLogIndicator.setLayout(infoLogIndicatorLayout);
        infoLogIndicatorLayout.setHorizontalGroup(
            infoLogIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        infoLogIndicatorLayout.setVerticalGroup(
            infoLogIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(messageIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(infoLogIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoLogSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageSwitch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLogIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLogSwitch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Interface");

        perceptSwitch.setText("Percepts");
        perceptSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perceptSwitchActionPerformed(evt);
            }
        });

        infoIndicator.setBackground(new java.awt.Color(255, 0, 0));
        infoIndicator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        infoIndicator.setPreferredSize(new java.awt.Dimension(22, 22));

        javax.swing.GroupLayout infoIndicatorLayout = new javax.swing.GroupLayout(infoIndicator);
        infoIndicator.setLayout(infoIndicatorLayout);
        infoIndicatorLayout.setHorizontalGroup(
            infoIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        infoIndicatorLayout.setVerticalGroup(
            infoIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        perceptIndicator.setBackground(new java.awt.Color(255, 0, 0));
        perceptIndicator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        perceptIndicator.setPreferredSize(new java.awt.Dimension(22, 22));

        javax.swing.GroupLayout perceptIndicatorLayout = new javax.swing.GroupLayout(perceptIndicator);
        perceptIndicator.setLayout(perceptIndicatorLayout);
        perceptIndicatorLayout.setHorizontalGroup(
            perceptIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        perceptIndicatorLayout.setVerticalGroup(
            perceptIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        infoSwitch.setText("Informations");
        infoSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoSwitchActionPerformed(evt);
            }
        });

        agentSwitch.setText("Agents");
        agentSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentSwitchActionPerformed(evt);
            }
        });

        agentIndicator.setBackground(new java.awt.Color(0, 255, 0));
        agentIndicator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        agentIndicator.setPreferredSize(new java.awt.Dimension(23, 23));

        javax.swing.GroupLayout agentIndicatorLayout = new javax.swing.GroupLayout(agentIndicator);
        agentIndicator.setLayout(agentIndicatorLayout);
        agentIndicatorLayout.setHorizontalGroup(
            agentIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        agentIndicatorLayout.setVerticalGroup(
            agentIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(agentIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agentSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(perceptIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(perceptSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(infoIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(perceptIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perceptSwitch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoSwitch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agentIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agentSwitch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(draw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(t1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(t1Win)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t2Win)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1)
                    .addComponent(t2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1Win)
                    .addComponent(t2Win))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(draw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void t1WinActionPerformed(java.awt.event.ActionEvent evt) {                                      
        _victory = t1.getText();
    }                                     

    private void t2WinActionPerformed(java.awt.event.ActionEvent evt) {                                      
        _victory = t2.getText();
    }                                     

    private void drawActionPerformed(java.awt.event.ActionEvent evt) {                                     
        _victory = "#draw#";
    }                                    

    private void perceptSwitchActionPerformed(java.awt.event.ActionEvent evt) {                                              
        _PERCEPT_VIEWER = !_PERCEPT_VIEWER;
       
        if(_PERCEPT_VIEWER){
        	perceptIndicator.setBackground(Color.GREEN);
        }else{
        	perceptIndicator.setBackground(Color.RED);
        }
    }                                             

    private void infoSwitchActionPerformed(java.awt.event.ActionEvent evt) {                                           
        _INFO_VIEWER = !_INFO_VIEWER;
        
        if(_INFO_VIEWER){
        	infoIndicator.setBackground(Color.GREEN);
        }else{
        	infoIndicator.setBackground(Color.RED);
        }
    }                                          

    private void messageSwitchActionPerformed(java.awt.event.ActionEvent evt) {                                              
        _MESSAGE_VIEWER = !_MESSAGE_VIEWER;
        
        if(_MESSAGE_VIEWER){
        	messageIndicator.setBackground(Color.GREEN);
        }else{
        	messageIndicator.setBackground(Color.RED);
        }
    }                                             

    private void agentSwitchActionPerformed(java.awt.event.ActionEvent evt) {                                            
        _AGENT_VIEWER = !_AGENT_VIEWER;
        
        if(_AGENT_VIEWER){
        	agentIndicator.setBackground(Color.GREEN);
        }else{
        	agentIndicator.setBackground(Color.RED);
        }
    }                                           

    private void infoLogSwitchActionPerformed(java.awt.event.ActionEvent evt) {                                              
        _INFO_LOG_VIEWER = !_INFO_LOG_VIEWER;
        
        if(_INFO_LOG_VIEWER){
        	infoLogIndicator.setBackground(Color.GREEN);
        }else{
        	infoLogIndicator.setBackground(Color.RED);
        }
    }                                             

    // Variables declaration - do not modify                     
    private javax.swing.JPanel agentIndicator;
    private javax.swing.JButton agentSwitch;
    private javax.swing.JButton draw;
    private javax.swing.JPanel infoIndicator;
    private javax.swing.JPanel infoLogIndicator;
    private javax.swing.JButton infoLogSwitch;
    private javax.swing.JButton infoSwitch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel messageIndicator;
    private javax.swing.JButton messageSwitch;
    private javax.swing.JPanel perceptIndicator;
    private javax.swing.JButton perceptSwitch;
    private javax.swing.JLabel t1;
    private javax.swing.JButton t1Win;
    private javax.swing.JLabel t2;
    private javax.swing.JButton t2Win;
    // End of variables declaration                   
}
