/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.turtlekit2.warbot.controller;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.sound.sampled.Clip;

/**
 * Classe permettant d'afficher l'equipe gagnante du match.
 * 
 * @author Bonnotte Jessy, Burc Pierre, Duplouy Olivier, Polizzi Mathieu
 *
 */
@SuppressWarnings("serial")
public class VictoryDialog extends javax.swing.JFrame {

	private Team						_Team = null;
	
    /**
     * Creates new form VictoryDialog
     */
    public VictoryDialog(Team team) {
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        _Team = team;
        _imageTeam.setIcon(_Team.getImage());
        _nameTeam.setText(_Team.getName());
        setLocationRelativeTo(null);
        
        jButton1.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				Controller._boucle = false;
				dispose();
				
			}
		});
    }
    
    @Override
    public void setVisible(boolean t){
    	super.setVisible(t);
    	
    	if(t && WarLauncher.getMusic()){
    		try{
	    		_Team.getClip().loop(Clip.LOOP_CONTINUOUSLY);
	    		_Team.getClip().start();
    		}catch(Exception e){
    			
    		}
    	}else{
    		try{
    			_Team.getClip().stop();
    		}catch(Exception e){
    			
    		}
    	}
    	
    }
    
    @Override
    public void dispose(){
    	try{
			_Team.getClip().stop();
		}catch(Exception e){
			
		}
    	super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _imageTeam = new javax.swing.JLabel();
        _nameTeam = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        _imageTeam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _imageTeam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        _nameTeam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setText("Ok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_imageTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(_nameTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(_imageTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_nameTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _imageTeam;
    private javax.swing.JLabel _nameTeam;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
